language: node_js
node_js:
  - "6"
addons:
  ssh_known_hosts: datasfexplorer.tk
before_install:
  - bash .travis/install.sh
script:
  - npm run test-travis
  - bash .travis/build.sh
after_success:
  - bash .travis/deploy.sh
