language: node_js
node_js:
- '6'
addons:
  ssh_known_hosts: datasfexplorer.tk
script:
- bash .travis/build.sh
deploy:
  skip_cleanup: true  // insures dist/ dir not to be deleted after npm test
  provider: script
  script:
  - bash .travis/deploy.sh
  on:
    all_branches: true
