language: node_js
node_js:
  - "6"
addons:
  ssh_known_hosts: datasfexplorer.tk
branches:
  only:
  - master
before_install:
  - bash .travis/install.sh
script:
 - bash .travis/build.sh
deploy:
  provider: script
  script: .travis/deploy.sh
  on:
    all_branches: true:

