language: node_js
node_js:
- '6'
cache:
  yarn: true
  directories:
    - node_modules
addons:
  ssh_known_hosts: datasfexplorer.tk
before_install:
  - bash .travis/install.sh
script:
- bash .travis/build.sh
after_success:
  - bash .travis/deploy.sh
