language: node_js
node_js:
- '6'
addons:
  ssh_known_hosts: datasfexplorer.tk
before_install:
- openssl aes-256-cbc -K $encrypted_5c93ddfc62aa_key -iv $encrypted_5c93ddfc62aa_iv
  -in travis_rsa.enc -out travis_rsa -d
- bash .travis/install.sh
script:
- bash .travis/build.sh
deploy:
  provider: script
  script:
  - bash .travis/deploy.sh
  on:
    all_branches: true
