language: node_js
node_js:
  - "0.12"
addons:
  ssh_known_hosts: datasfexplorer.tk
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_5c93ddfc62aa_key -iv $encrypted_5c93ddfc62aa_iv
  -in deploy/travis_rsa.enc -out deploy/travis_rsa -d
- chmod 600 deploy/travis_rsa
script:
- npm run build
deploy:
  provider: script
  script: deploy/server_deploy.sh
  on:
    all_branches: true
