language: node_js
node_js:
  - "0.12"
addons:
  ssh_known_hosts: datasfexplorer.tk
branches:
  only:
  - master
before_install:
- bash deploy/install.sh
script:
- npm run build
deploy:
  provider: script
  script: deploy/server_deploy.sh
  on:
    all_branches: true
