language: node_js
node_js:
- '6'
addons:
  ssh_known_hosts: datasfexplorer.tk
install: echo "skip install"
before_install:
- bash .travis/install.sh
script:
- bash .travis/build.sh
deploy:
  provider: script
  script:
  - bash .travis/deploy.sh
