language: node_js
node_js:
- '6'
addons:
  ssh_known_hosts: datasf-explorer.tk
before_install:
- bash .travis/install.sh
script:
- bash .travis/build.sh
before_deploy:
- bash .travis/setup_ssh_agent.sh
deploy:
  skip_cleanup: true  // insures dist/ dir not to be deleted after npm test
  provider: script
  script:
  - bash .travis/deploy.sh
  on:
    all_branches: true
